# VoxelTree Configuration - Phase 0B World Generation Bootstrap
# This file defines parameters for Minecraft world generation and training

worldgen:
  seed: "VoxelTree"  # Converts to 1903448982
  java_heap: "4G"
  batch_size: 16     # Chunks per .mca generation batch
  max_temp_disk_gb: 5
  chunk_region_bounds:
    x_min: 0
    x_max: 128        # 2048 chunks = 128 regions
    z_min: 0  
    z_max: 128
  java_tools:
    primary: "tools/minecraft-worldgen.jar"
    fallback: "tools/fabric-worldgen-mod.jar"

# Training configuration (for later phases)
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  device: "cuda"  # or "cpu"
  
# Data configuration
data:
  chunk_format: "npz"  # Compressed numpy format
  max_chunks_in_memory: 1000
  temp_data_dir: "data/temp"
  processed_data_dir: "data/processed"
