# VoxelTree Configuration - Phase 0B World Generation Bootstrap
# This file defines parameters for Minecraft world generation and training

worldgen:
  seed: "VoxelTree"  # Converts to 1903448982
  java_heap: "4G"
  batch_size: 16     # Chunks per .mca generation batch
  max_temp_disk_gb: 5
  chunk_region_bounds:
    x_min: 0
    x_max: 128        # 2048 chunks = 128 regions
    z_min: 0  
    z_max: 128
  java_tools:
    primary: "tools/minecraft-worldgen.jar"
    fallback: "tools/fabric-worldgen-mod.jar"

# Extraction configuration (Phase 0C)
extraction:
  output_dir: "data/chunks"
  temp_dir: "temp_extraction"
  max_disk_usage_gb: 10
  batch_size: 64              # chunks per batch before disk write
  num_workers: 4              # multiprocessing workers
  compression_level: 6        # npz compression (1-9)
  validation:
    verify_checksums: true
    detect_corruption: true
  block_mapping:
    air_blocks: [0]           # block IDs considered "air"
    solid_blocks: [1, 2, 3]   # common solid block IDs
  heightmap:
    surface_blocks: [2, 3, 4] # blocks that count as "surface"
    min_height: -64           # world bottom (Y coordinate)
    max_height: 320           # world top (Y coordinate)

# Training configuration (for later phases)
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  device: "cuda"  # or "cpu"
  
# Data configuration
data:
  chunk_format: "npz"  # Compressed numpy format
  max_chunks_in_memory: 1000
  temp_data_dir: "data/temp"
  processed_data_dir: "data/processed"
