[tool.black]
line-length = 100
target-version = ['py311']
skip-string-normalization = false

[tool.flake8]
ignore = ["E226", "W503"]
max-line-length = 100

[tool.mypy]
ignore_missing_imports = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = "yaml"
ignore_missing_imports = true
