name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Lint + Typecheck + Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy pytest

      - name: Check formatting with black
        run: black --check .

      - name: Lint with flake8
        run: flake8 .

      - name: Type check with mypy
        run: mypy src tests

      - name: Run unit tests
        run: pytest --tb=short --disable-warnings

      - name: Check code coverage
        run: |
          pip install pytest-cov
          pytest --cov=src --cov=tests --cov-report=term-missing