
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Lint + Typecheck + Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy pytest pytest-cov

      - name: Set PYTHONPATH
        shell: bash
        run: echo "PYTHONPATH=${PYTHONPATH};${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV

      - name: Check formatting with black
        shell: bash
        run: black --check .

      - name: Type check with mypy
        shell: bash
        run: mypy --ignore-missing-imports --explicit-package-bases scripts tests

      - name: Run unit tests
        shell: bash
        run: pytest --tb=short --disable-warnings

      - name: Check code coverage
        shell: bash
        run: pytest --cov=scripts --cov-report=term-missing